### PR TITLE
Fixes observatory not observing.

### PR DESCRIPTION
**Pull request by Thutmose**
This should deal with #897 for the 1.11 branch, this fix can then be merged to 1.12 to fix it there

### CODE REVIEW

**Comment by Thutmose** [comment]
why does it say the check failed, yet the other says no conflicts?

**Comment by dmodoomsirius** [comment]
Its a gradle thing. do not worry. Its not failing due to code related issues.

**Comment by zmaster587** [comment]
I would suspect the changelog thing again.  But anyway, two prevent two copies of disscussion and for the sake of keeping things organized, I did post the reasoning in #897 for why data isn't collected

**Comment by Thutmose** [comment]
Ahh, if the observatory thingy is intended, then I shall close this PR, I had just used a sat to collect the distance data to test asteroid stuff anyway :D

**Pull request closed without merging**
