### PR TITLE
Fixed "Unable to tick satellites on dedicated server"

### PR DESCRIPTION
**Pull request by StannisMod**
- Added copying ticking satellites while copying the whole dimension (performs only on dedicated server)
- Added packet to sync dimension's ticking satellites on tick
- Code style... Ctrl+Shift+L

Also fixed issue with auto-downloading libVulpez from maven that don't work for me (download timeout error), now you should place its deobf version to `libs` in the root of the repository

### CODE REVIEW

**Comment by ReiDaTecnologia** [comment]
Thx for fixing Satellites on servers m8 :D
Now fix space elevator :P

**Comment by StannisMod** [comment]
> Thx for fixing Satellites on servers m8 :D Now fix space elevator :P

Pls give me a link for the corresponding issue

**Comment by ReiDaTecnologia** [comment]
> > Thx for fixing Satellites on servers m8 :D Now fix space elevator :P
> 
> Pls give me a link for the corresponding issue

I was mainly joking but thx if u fix it
There isn't an issue that cover all the issues but the Space Elevator's wiki page list (hopefully) all of them but as the wiki is offline (again bruh), i will just say it here:
- When entering the capsule, it may tell you that the space elevator is turned off but you can still use it (You cant disable it as it always comeback to off when trying to turning it on in the gui). You may need to press the on/off button at least once for it to transport you.
- After the first use, the tether may disappears and never appear again (until you break the multiblock and build it again) or simply never appear.
- When going down the space elevator, you will receive fall damage and possibly die because of it.

**Comment by StannisMod** [comment]
> I was mainly joking but thx if u fix it

It is in my best interest because I am going to make interesting appearance and opportunities on my private server :)

**Comment by voidsong-dragonfly** [comment]
You changed 500 files. _Absolutely not._ You will remake this PR without the massive changes to half a thousand files and with just the necessary changes.

**Comment by Chozo-Varia** [comment]
Hey, I don't know much about programming. I have now seen that you seem to have changed the code of the mod, but I don't understand where and how I can download your modified mod now.

**Comment by Moose1002** [comment]
@StannisMod Is there any chance you could remake this without all the file changes? It's crazy that this pretty huge bug has gone unfixed for like 2 years now, and I'd love to finally see a fix for it merged.

**Pull request closed without merging**
