### PR TITLE
Bipropellant fuels for rockets

### PR DESCRIPTION
**Pull request by Silfryi**
- Adds bipropellant fuels
 - Fuel combos are exclusive, you cannot have three types of monopropellant or six types of bipropellant in the same rocket
 - Oxidizers, bipropellant fuels, and monopropellant fuels now can have their consumption in the rocket configured in the config - per fuel
 - Rocket fuel will work as normal, but Hydrogen and Oxygen input separately can now be used
 - Bipropellant fuel bars are fuel + oxidizer, so half full of each is half, same as full of one and empty of the other

### CODE REVIEW

**Comment by tabr** [comment]
I've try this fork for 1.12. But is works very strange: The Rocket GUI does not recognize fuel. The rocket can contain only 1 rocket tank.
I think: It is not ready.

**Comment by Silfryi** [comment]
1) is known and only happens for monopropellants, I have not found the reason yet. 2).... _what_? I've literally tested this and they can contain as many tanks as they want.

**Comment by tabr** [comment]
> 1. is known and only happens for monopropellants, I have not found the reason yet. [Edit: this seems to be fixed now]
>    2).... _what_? I've literally tested this and they can contain as many tanks as they want.

Oh i mean... it doesn't matter how many tanks have a rocket one or many. It will pass all checks for fuel capacity and will be built. And will start.

**Comment by Silfryi** [comment]
So I'm still confused, are you saying that the checks for fuel capacity aren't rigorous enough?

**Comment by tabr** [comment]
> So I'm still confused, are you saying that the checks for fuel capacity aren't rigorous enough?

I don't know why is started. What i do:
1st i build a rocket in standard AR, there wat 2 engine, 4-6 fuel tanks, satellite bay.
Next i've build your branch, and there was enough 1 tank. And a rocket was launched.

**Comment by Silfryi** [comment]
I found the bug, it pulls the wrong rate (and since I changed nothing else; that rocket would technically be viable in standard AR if it let you build)

**Comment by Silfryi** [comment]
@tabr which should be fixed now :)

**Review by zmaster587 — APPROVED** [review]

**Pull request merged**
