### PR TITLE
fixes a bunch of missing rolling machine recipes.

### PR DESCRIPTION
**Pull request by Thutmose**
the recipes for plates and sheets in the rolling machine didn't seem to be in or working in 1.12, so I added them next to the tank ones, if there was somewhere else they were supposed to be, please let me know.

### CODE REVIEW

**Comment by zmaster587** [comment]
The plates and sheets should be taken care of in zmaster587.advancedRocketry.util.RecipeHandler which is where the autogenerated recipes are taken care of for mod compat.  Reason for the seperation is that the majority of machine recipes should be loaded fairly early, but items from other mods may not be availible yet, and at the same time it makes more sense and is cleaner to load all the generalized ore stuff all at once to prevent the requirement for a check if it's AR and load elsewhere.  Since AR ore dict items are also counted, they also get loaded up.  

So it looks like there's a failure there too, that may cascade to nearly every other machine in the mod.  From the looks of it, there's a big TODO there, so that may actually be the issue.

**Comment by Thutmose** [comment]
Ahh, I shall look into what is needed to fix it there then, and will remove the manual stuff in the rolling machine itself

**Comment by zmaster587** [comment]
I'm thinking it might be tricky because it's looking like a lot of the oredict recipes got moved over to JSON and I had used oredict recipes rather heavily.  It may be a bit messy since there's the XML recipe system in AR too, and that won't be covered by the JSON in all cases AFAIK.

**Comment by zmaster587** [comment]
Nevermind, I'm an idiot, missed the GameData.register_impl method.

**Comment by Thutmose** [comment]
I got it somewhat working, however it seems to be registering some of the ingot -> plate recipes twice atm

**Comment by Thutmose** [comment]
currently there is this recipe in JEI however:
image
it seems to have no inputs, the gas recipes also look like no inputs, but hovoring over the slots shows the correct tooltips:
image
image

**Comment by zmaster587** [comment]
That last one looks more like the fluid render thing broke, though im not sure what's wrong with that first image right now.  I'm looking over the commit you made atm too.

**Comment by zmaster587** [comment]
I do remember running into the fluid issue way back in 1.10 with JEI, I don't recall how it was fixed though.

**Comment by Thutmose** [comment]
what is the timing on the jenkins build server, ie does it check for a build from commits every so often?

I have never used one for building before, so not sure how they work.

**Comment by zmaster587** [comment]
It checks every 24 hours currently for changes.  

Also I fixed both the fluids and cartridge recipes.  I totally forgot that damages are stored as shorts and not ints, so the large damage value kinda messed with things.  As for the fluids, turns out the capacity of the object in JEI just needed to be set to 1.

**Pull request merged**
