### PR TITLE
Change Localizations to be Clearer (en_US)

### PR DESCRIPTION
**Pull request by Silfryi**
Current Changes:
 - 'Moon Turf' Blocks are now Regolith to make them more ambiguous and better suited for other planets
 - All of the crystal blocks are named after the gems in a hopefull non-ambiguous way without conflicts
 - A couple of changes to improve cohesion

### CODE REVIEW

**Comment by zmaster587** [comment]
I think I'd like to keep "some random data" in some form.  It was aimed to be more of a funny  message than serious.  "Some random data but it makes no sense to you" would work too if it's more clear if "some random data" isn't good enough..

**Comment by Silfryi** [comment]
People had been confused in the past, how about "No Data Present, or maybe you can't see it..."?

**Comment by Silfryi** [comment]
Actually nevermind, that's confusing too. Try "Lack of Intelligible Data"

**Comment by zmaster587** [comment]
That works

**Comment by Silfryi** [comment]
Done

**Pull request merged**
